apiVersion: v1
kind: PersistentVolume
metadata:
  name: alpinevol
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi #Size of the volume
  accessModes:
    - ReadWriteOnce #type of access
  hostPath:
    path: "/KubeStorage/alpine" #host location
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: alpinevol
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

